name: Run Tests 

on:
  push:
    paths:
      - "sense_web/**"
      - "tests/**"
  pull_request:
    paths:
      - "sense_web/**"
      - "tests/**"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"

      - name: Set up Python
        run: uv python install
      
      - name: Install dependencies
        run: uv pip install .[dev]
      
      - name: Run tests
        run: pytest -vv tests
